🔨 Up: Workflow upload coverage tests button

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -8,72 +8,72 @@ env:
   EXECUTABLES: "template, lib/libmy.a, lib/libchained_list.a"
 
 jobs:
-  Check_coding_style:
-    runs-on: ubuntu-latest
-    name: Check for Epitech coding-style
-    continue-on-error: false
-    container:
-      image: ghcr.io/epitech/coding-style-checker:latest
-      volumes:
-        - "coding-style_volume:/volume_mount"
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Coding style
-        run: |
-            check.sh $(pwd) $(pwd)
-            echo "error_style_count=$(wc -l coding-style-reports.log | cut -d" " -f1)" >> "$GITHUB_OUTPUT"
-      - name: show error
-        if: steps.run-coding-style.outputs.error_style_count > 0
-        run: |
-          awk -F":" '{print "::error file="$1",line="$2",title="$3" coding style error::"$4}' coding-style-reports.log
-          exit 1
+#   Check_coding_style:
+#     runs-on: ubuntu-latest
+#     name: Check for Epitech coding-style
+#     continue-on-error: false
+#     container:
+#       image: ghcr.io/epitech/coding-style-checker:latest
+#       volumes:
+#         - "coding-style_volume:/volume_mount"
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v3
+#       - name: Coding style
+#         run: |
+#             check.sh $(pwd) $(pwd)
+#             echo "error_style_count=$(wc -l coding-style-reports.log | cut -d" " -f1)" >> "$GITHUB_OUTPUT"
+#       - name: show error
+#         if: steps.run-coding-style.outputs.error_style_count > 0
+#         run: |
+#           awk -F":" '{print "::error file="$1",line="$2",title="$3" coding style error::"$4}' coding-style-reports.log
+#           exit 1
 
-  Check_program_compilation:
-    runs-on: ubuntu-latest
-    name: Check if the program compile correctly
-    needs: Check_coding_style
-    continue-on-error: false
-    container:
-      image: epitechcontent/epitest-docker:latest
-      volumes:
-        - "compilation-volume:/volume_mount"
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Chech the program compilation
-        run: make
-        timeout-minutes: 2
-      - name: Check the cleaning
-        run: make clean
-      - name: Check for all executables
-        run: |
-            IFS=", ";
-            for file in $EXECUTABLES; do
-              if [ ! -x "$file" ]; then
-                echo "$file doesn't exist !"
-                exit 1
-              fi
-              exit 0
-            done
+#   Check_program_compilation:
+#     runs-on: ubuntu-latest
+#     name: Check if the program compile correctly
+#     needs: Check_coding_style
+#     continue-on-error: false
+#     container:
+#       image: epitechcontent/epitest-docker:latest
+#       volumes:
+#         - "compilation-volume:/volume_mount"
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v3
+#       - name: Chech the program compilation
+#         run: make
+#         timeout-minutes: 2
+#       - name: Check the cleaning
+#         run: make clean
+#       - name: Check for all executables
+#         run: |
+#             IFS=", ";
+#             for file in $EXECUTABLES; do
+#               if [ ! -x "$file" ]; then
+#                 echo "$file doesn't exist !"
+#                 exit 1
+#               fi
+#               exit 0
+#             done
 
-  Run_tests:
-    runs-on: ubuntu-latest
-    name: Run all tests
-    needs: Check_program_compilation
-    container:
-      image: epitechcontent/epitest-docker:latest
-      volumes:
-        - "tests-volume:/volume_mount"
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Run the unitary tests
-        run: make re tests_run
-        timeout-minutes: 2
-      - name: Run the functional tests
-        run: make re tests_functional
-        timeout-minutes: 2
+#   Run_tests:
+#     runs-on: ubuntu-latest
+#     name: Run all tests
+#     needs: Check_program_compilation
+#     container:
+#       image: epitechcontent/epitest-docker:latest
+#       volumes:
+#         - "tests-volume:/volume_mount"
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v3
+#       - name: Run the unitary tests
+#         run: make re tests_run
+#         timeout-minutes: 2
+#       - name: Run the functional tests
+#         run: make re tests_functional
+#         timeout-minutes: 2
 
   Upload_coverage:
     runs-on: ubuntu-latest
@@ -122,24 +122,15 @@ jobs:
           echo "COVERAGE_BRANCHES=$coverage_branches" >> $GITHUB_ENV
           echo "COVERAGE=$coverage" >> $GITHUB_ENV
 
-      - name: Generate coverage branches badge
-        uses: fregante/action-shields-badge@v1
+      - name: Create Awesome Badge
+        uses: schneegans/dynamic-badges-action@v1.6.0
         with:
-          label: Coverage
-          message: ${{ env.COVERAGE_BRANCHES }}%
-          color: brightgreen
-      - name: Generate coverage badge
-        uses: fregante/action-shields-badge@v1
-        with:
-          label: Coverage
-          message: ${{ env.COVERAGE }}%
-          color: brightgreen
-
-      - name: Update README
-        run: |
-          sed -i 's|<a href="https://github.com/Morilhat-Paul/Test_repo/actions/workflows/workflow.yaml"><img src="https://github.com/Morilhat-Paul/Test_repo/actions/workflows/workflow.yaml/badge.svg" /></a>|<a href="https://github.com/Morilhat-Paul/Test_repo/actions/workflows/workflow.yaml"><img src="https://img.shields.io/endpoint?url=https%3A%2F%2Fshields-badge-xyz123.herokuapp.com%2Fbadge%2FCoverage%2F${{ env.COVERAGE_PERCENTAGE }}%2Fbrightgreen"></a>|' README.md
-      - name: Commit and push changes
-        run: |
-          git add README.md
-          git commit -m ":memo: Up: Coverage badge"
-          git push
+          auth: ${{ secrets.GIST_SECRET }}
+          gistID: ef0cca4079ae9a36ebea3cbdd3b1c4d4
+          filename: coverag_branches.json
+          label: Hello
+          message: ${{ env.COVERAGE_BRANCHES }}
+          valColorRange: ${{ env.COVERAGE_BRANCHES }}
+          orangeminColorRange: 50
+          maxColorRange: 90
+          forceUpdate: true
